spring:
  debug: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:marvel
    driverClassname: org.h2.Driver
    user: sa
    password: password
    data: classpath*:resources/data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.H2Dialect
    property-naming-strategy: SNAKE_CASE
server:
  port: 8100
constants:
  mapBrands :
    visa: com.fiserv.posnet.service.impl.CalculateRateTaxVisaImpl
    amex: com.fiserv.posnet.service.impl.CalculateRateTaxAmexImpl
    naranja: com.fiserv.posnet.service.impl.CalculateRateTaxNaranjaImpl
  amountMaximum:
    1000.00