spring:
  debug: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://postgresdb:5432/pruebas
    username: pruebas
    password: administracion
    initialization-mode: always
    data: classpath*:resources/data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    property-naming-strategy: SNAKE_CASE
server:
  port: 8100
constants:
  mapBrands :
    visa: com.fiserv.posnet.service.impl.CalculateRateTaxVisaImpl
    amex: com.fiserv.posnet.service.impl.CalculateRateTaxAmexImpl
    naranja: com.fiserv.posnet.service.impl.CalculateRateTaxNaranjaImpl
  amountMaximum:
    1000.00